// Each step: target (CSS selector or null), title, body,
// and optional side-effects: year, tab, layer (object), compartment (key string)
export const TOUR_STEPS = [
  {
    target: null,
    title: '🌊 HHE Lab Sardinia — Dashboard Tour',
    body: '6-year analysis of marine litter hazard along the Sardinian coast (2018–2023), MSFD Descriptor 10. This tour walks through every feature. Press Next or use ← → arrow keys.',
  },
  {
    target: '.chip.red',
    title: '🏖 Max Beach Litter',
    body: 'Peak items/100m across all beach transects for the selected year. Sparkline shows the 2018–2023 trend. ↑/↓ badge = year-on-year change. Best/worst year tags below.',
    year: 2019,
  },
  {
    target: '.chip.grn',
    title: '🌀 Sea Current Speed',
    body: 'Annual mean surface current speed (cm/s) from CMEMS data. Used as hazard amplifier — faster currents = higher dispersal capacity. Peak in 2022.',
    year: 2022,
  },
  {
    target: '.chip.pur',
    title: '🧴 Plastic Fraction',
    body: '% of floating litter classified as artificial polymer. Near 100% in 2018, declining trend. Spearman r = −0.66 vs current speed: faster water disperses plastic away from transects.',
    year: 2018,
  },
  {
    target: '.chip.org',
    title: '🦎 Biological Impact Score',
    body: 'Impact proxy from CNR-IAS Oristano sea turtle (Caretta caretta) stranding data. Combines entanglement + ingestion events, normalised to historical max. Peak: 2021.',
    year: 2021,
  },
  {
    target: '.chip.comp',
    title: '📊 Composite Hazard Score',
    body: 'Weighted combination of all 4 components: Beach litter 35% + Plastic 25% + Currents 20% + Bio 20%. Single number summarising overall hazard pressure for the year.',
    year: 2021,
  },
  {
    target: '.year-bar',
    title: '📅 Year Slider & Playback',
    body: 'Drag to select year 2018–2023. Hit ▶ to auto-animate across all years. The colour badge shows the period context: pre-COVID / COVID / post-COVID.',
    year: 2020,
  },
  {
    target: '.tab-bar',
    title: '📂 Analytical Tabs',
    body: '5 data compartments in the right panel: Beach litter transects, Floating litter composition, Tourism correlation, Sea currents time-series, Biological impact (turtles).',
    tab: 'beach',
    year: 2019,
  },
  {
    target: '.tab-btn:nth-child(1)',
    title: '🏖 Beach Litter Tab',
    body: 'Per-beach bar chart with EU threshold line (150 items/100m). Stat cards show survey count, beaches above threshold, mean density. 6 monitoring stations across Sardinia.',
    tab: 'beach',
    year: 2019,
  },
  {
    target: '.tab-btn:nth-child(2)',
    title: '🌊 Floating Litter Tab',
    body: 'Material composition pie chart for the selected year. Below: Spearman correlation matrix between beach litter, floating litter, tourism, and current speed.',
    tab: 'float',
    year: 2021,
  },
  {
    target: '.tab-btn:nth-child(3)',
    title: '🧳 Tourism vs Litter',
    body: 'Dual-axis chart: beach litter density (bars) vs tourist arrivals in millions (line). Pearson r = −0.44 — counter-intuitive: more tourists → more cleaning → lower measured litter.',
    tab: 'tourism',
  },
  {
    target: '.tab-btn:nth-child(4)',
    title: '🌀 Surface Currents Tab',
    body: 'Monthly CMEMS current speed 2018–2023. Compass shows mean annual direction. Reference line marks the selected year. Spearman r = −0.66 vs floating litter.',
    tab: 'currents',
    year: 2022,
  },
  {
    target: '.tab-btn:nth-child(5)',
    title: '🦎 Biological Impact Tab',
    body: 'Entanglement events by year (stacked by clinical condition) + plastic ingestion by material type. Bio Score gauge and trend line. ~99% Caretta caretta, 83+82 total events.',
    tab: 'biological',
    year: 2021,
  },
  {
    target: '.topbar-right',
    title: '🗺 Map Layer Controls',
    body: 'Toggle overlays on the map: ~ Currents (CMEMS velocity vectors), 🗺 Segments (comuni hazard choropleth), 🔴 LISA (spatial autocorrelation — HH/LL hotspots and coldspots).',
    layer: { comuni: true, curr: false, lisa: false },
    tab: 'beach',
    year: 2019,
  },
  {
    target: '.map-bg',
    title: '🗺 Comuni Hazard Map',
    body: 'Each coastal municipality coloured by composite hazard score. Hover to see name + value. The IDW interpolation propagates beach station measurements to all 377 comuni.',
    layer: { comuni: true, curr: false, lisa: false },
    year: 2019,
  },
  {
    target: '.topbar-right',
    title: '🔴 LISA Spatial Clusters',
    body: 'Local Indicators of Spatial Association. Red = HH hotspot (high hazard surrounded by high), Blue = LL coldspot. Global Moran\'s I ≈ 0.97 → strongly clustered pattern.',
    layer: { comuni: true, curr: false, lisa: true },
    year: 2019,
  },
  {
    target: '.add-compartment-wrap',
    title: '➕ Extensible Compartments',
    body: 'Add optional data panels not included in the main tabs. Currently available: Microplastics IDW concentration grid from 7,913 ISPRA surface trawl samples (336 cells/year).',
    layer: { comuni: true, curr: false, lisa: false },
    compartment: 'micro',
  },
  {
    target: '.addon-panel',
    title: '🔬 Microplastics Panel',
    body: 'IDW-interpolated mean density per year from >7,900 ISPRA trawl samples. 336-cell grid (0.12°×0.12°, ~11km/cell). Demonstrates how new compartments slot into the dashboard.',
    compartment: 'micro',
  },
  {
    target: '.insights-panel',
    title: '📊 Auto-Insights',
    body: 'Automatically generated highlights: peak/best year per variable, % trend 2020→2023, max biological impact. Scroll the panel to see all. Also available in the ℹ modal.',
  },
  {
    target: null,
    title: '✅ Tour Complete',
    body: 'You\'ve seen the full dashboard. Use 🇮🇹/🇬🇧 to switch language, ⛶ for fullscreen, 📸 to export a screenshot. Data: ISPRA, CNR-IAS, CMEMS (2018–2023).',
  },
];
